# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: haukes blog
tagline: ...nur ein bisschen wirres zeug...
email: hauke@h-dawg.de
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.h-dawg.de" # the base hostname & protocol for your site
twitter_username: hwesselmann
github_username:  hwesselmann
gitlab_username: hwesselmann

permalink: /:title/

# Build settings
markdown: kramdown

# Plugins
gems: ["jekyll-paginate"]

# Pagination
paginate: 5
paginate_path: "page/:num/"
